# encoding:utf-8
"""
Django settings for commmunity_resource_share project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
# import djcelery
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from celery import Celery,platforms

platforms.C_FORCE_ROOT = True  #以root权限

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!gs^ehekpyuc4%s7e-ayi12+1yl!+ou_cfq2&(=wxxh@%6is_0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# BROKER_URL = 'redis://127.0.0.1:6379/2'
# BROKER_TRANSPORT = 'redis'

# Application definition

INSTALLED_APPS = (
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'kombu.transport.django',
    'rest_framework',
    'djcelery',
    'notifications',
    'ckeditor',
    'ckeditor_uploader',
    'xadmin',
    'crispy_forms',
    'contact',
    'accounts',
    'article',
    'comments',
    'community',
    # 'help_center',
    'order',
    'resources',
    # 'service',
)

MIDDLEWARE_CLASSES = (
    # 'django.middleware.cache.UpdateCacheMiddleware',    # This must be first on the list
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',    # 处理gzip压缩,减轻服务器压力
    # 'django.middleware.cache.FetchFromCacheMiddleware', # This must be last
    'middleware.disablecsrf.DisableCSRFCheck',
)

ROOT_URLCONF = 'commmunity_resource_share.urls'

NOTIFICATIONS_SOFT_DELETE=True

AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = (('django.contrib.auth.backends.ModelBackend'))

CORS_ORIGIN_ALLOW_ALL=True

CORS_ALLOW_CREDENTIALS=True

ALLOWED_HOSTS = (
    'localhost:8080',
    'localhost:8082',
    '127.0.0.1:8000',
    '127.0.0.1:8002',
)

CORS_ORIGIN_WHITELIST = (
    '127.0.0.1:8000',
    'localhost:8082',
    'localhost:8080'
)

CORS_ALLOW_METHODS = (
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'accept-language',
    'cache-control',
    'authorization',
    'content-type',
    'dnt',
    'cookie',
    'host',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "static")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

IS_CLOSE_CSRF = True


WSGI_APPLICATION = 'commmunity_resource_share.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default':{
        'ENGINE':'django.db.backends.mysql',
        'NAME':'communityshare',
        'USER':'root',
        'PASSWORD':'8782',
        'HOST':'127.0.0.1',
        'PORT':'3306',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_MODEL_SERIALIZER_CLASS': 'rest_framework.serializers.HyperlinkedModelSerializer',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,      #page_size
    'DATETIME_FORMAT': ("%Y-%m-%d %H:%M:%S"),

}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR,'static')

STATICFILES_DIRS = (
    # ("imgs", os.path.join(STATIC_ROOT, 'imgs')),
    # # ("static", os.path.join(STATIC_ROOT, 'static')),
    # ("pdf", os.path.join(STATIC_ROOT, 'pdf')),
    # ("down", os.path.join(STATIC_ROOT, 'down')),
    # ("img", os.path.join(STATIC_ROOT, 'img')),
    ("dist", os.path.join(STATIC_ROOT, 'dist')),
    ("dist/static", os.path.join(STATIC_ROOT, 'dist/static')),
)

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
    os.path.join(BASE_DIR, 'tempaltes/'),
)


#本地开发
# CACHES = {
#     'default': {
#         'BACKEND': 'redis_cache.RedisCache',
#         'LOCATION': '127.0.0.1:6379',
#
#     }
# }

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "REDIS_CLIENT_CLASS": "fakeredis.FakeStrictRedis",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "SOCKET_CONNECT_TIMEOUT": 5,  # in seconds
            "SOCKET_TIMEOUT": 5,  # in seconds
            "PICKLE_VERSION": -1 , # Use the latest protocol version
            # "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "IGNORE_EXCEPTIONS": True,#忽略连接异常
        }
    }
}


CACHE_MIDDLEWARE_ANONYMOUS_ONLY=True  #只有匿名请求（即不是由登录的用户）将被缓存

DJANGO_REDIS_IGNORE_EXCEPTIONS = True    #所有配置的高速缓存,忽略连接异常

DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True #登录忽略例外

SESSION_ENGINE = "django.contrib.sessions.backends.cache"

SESSION_CACHE_ALIAS = "default"

'''
三个URL方案的支持：

redis://：创建一个正常的TCP套接字连接

rediss://：创建一个SSL包裹的TCP套接字连接

unix:// 创建一个Unix域套接字连接

有几种方法来指定数据库编号：

一个db查询字符串的选项，例如Redis的：//本地主机DB = 0

如果使用Redis的：//方案，URL的路径参数，例如： redis://localhost/0
'''


#邮件配置
EMAIL_HOST = 'smtp.163.com'                   #SMTP地址
EMAIL_PORT = 25                                 #SMTP端口
EMAIL_HOST_USER = '13540354036@163.com'       #我自己的邮箱
# EMAIL_HOST_PASSWORD = 'flzx3000c'                  #我的邮箱密码
EMAIL_HOST_PASSWORD = 'lyc123'                  #我的邮箱密码
EMAIL_SUBJECT_PREFIX = u'[社区资源共享]'            #为邮件Subject-line前缀,默认是'[django]'
EMAIL_USE_TLS = True                             #与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false
DEFAULT_FROM_EMAIL = '13540354036@163.com'
#管理员站点
SERVER_EMAIL = '13540354036@163.com'



#注意！ media 目录与 CKEDITOR_UPLOAD_PATH 是相对的所以：
# Ckeditor settings
CKEDITOR_UPLOAD_PATH = "uploads/"  # 他的目录相对与media root 就是 media root + CKEDITOR_UPLOAD_PATH 不能写成"/uploads/"
CKEDITOR_JQUERY_URL = 'js/jquery.min.js'
CKEDITOR_IMAGE_BACKEND = 'pillow'  # 图像库支持需要安装 PIL

# 这个设置看你的偏好。。。仅仅是一个exsample
CKEDITOR_CONFIGS = {
    'default': {
        'update': ['Image', 'Update', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'],
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join(
            [
                # your extra plugins here
                'div',
                'autolink',
                'autoembed',
                'embedsemantic',
                'autogrow',
                # 'devtools',
                'widget',
                'lineutils',
                'clipboard',
                'dialog',
                'dialogui',
                'elementspath'
            ]),
    }
}
CKEDITOR_ALLOW_NONIMAGE_FILES = False